Repository Real-Dev-Squad/website-crypto, pull requests merged in 2020-11, with the labels that each got.

#52 Layoutchange/responsive
  components/coins-status/index.js
  components/filter/index.js
  components/transaction-chart/index.js
  components/transaction-details/index.js
  components/user-info/index.js
  mock/passbookData.json
  mock/transaction-graph-data.json
  package-lock.json
  pages/cart.js
  pages/index.js
  styles/Home.module.css
Labels: feature-task, hacktoberfest

#56 fix useEffect infinite calling for transaction chart #0
  components/transaction-chart/index.js
Labels: bug

#61 Footer given a margin on bottom, base url updated for compiler options
  jsconfig.json
  styles/globals.css
Labels: enhancement
