Repository Real-Dev-Squad/website-crypto, pull requests merged in 2021-03, with the labels that each got.

#165 Auctions Page
  .env.production
  components/Auctions/Auctions.module.css
  components/Auctions/createNewAuction.js
  components/Auctions/index.js
  components/Auctions/new.module.css
  constants.js
  package-lock.json
  pages/auctions/index.js
  pages/auctions/new.js
  public/assets/gem.png
  utils/fetchData.js
  utils/fetchSelfDetails.js
Labels: feature task

#170 fixed interger conversion bug and navbar
  components/Auctions/index.js
  components/NavBar/index.js
Labels: bug

#158 PR for Creating investing page on crypto site
  components/NavBar/index.js
  components/stock-card/index.js
  components/stock-operation-modal/index.js
  components/stock-operation-modal/stock-operation.module.css
  components/stock-operation/index.js
  mock/stocks.json
  pages/trading/index.js
  public/assets/stocks.jpg
  redux/action.js
  redux/reducers/index.js
  redux/reducers/stocksDetails.js
Labels: WIP, frontend

#176 Fixes favicon, title of auctions page, integrates wallet and minor changes in auctions page
  components/Auctions/createNewAuction.js
  components/Auctions/index.js
  pages/auctions/index.js
  pages/auctions/new.js
  public/favicon.ico
Labels: bug-fix

#180 Cosmetic cleanup for one year launch
  components/NavBar/index.js
  components/NavBar/navbar.module.css
  components/coins-status/coin.module.css
  components/coins-status/index.js
  pages/index.js
  styles/Home.module.css
  styles/globals.css
Labels: frontend

#183 Integrating /wallet API
  components/coins-status/coin.module.css
  components/coins-status/index.js
  constants.js
Labels: feature task, frontend

#191 Checks if user has sufficient neelams to sell in auctions
  components/Auction/Auction.module.css
  components/Auction/createNewAuction.js
  components/Auction/index.js
  components/Auction/new.module.css
  components/NavBar/index.js
  constants.js
  pages/auction/index.js
  pages/auction/new.js
Labels: bug
